fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'ui-template'
author 'Generated by Assistant'
description 'React + Vite + Tailwind NUI template'
version '0.0.1'

ui_page 'web/dist/index.html'

files {
	'web/dist/index.html',
	'web/dist/assets/**'
}

client_scripts {
	'client/main.lua'
}


